menus:
  - id: mainmenu_anon
    title: Main menu
    entries:
      - key: l
        name: login
        actions:
          - Login
      - key: r
        name: register
        actions:
          - Register
      - key: w
        name: watch games in progress
        actions:
          - Watch
      - key: q
        name: quit
        actions:
          - Quit
  - id: mainmenu_user
    title: Main menu
    entries:
      - key: c
        name: change current password
        actions:
          - ChangePassword
      - key: e
        name: change current contact information
        actions:
          - ChangeContact
      - key: n
        name: NetHack 3.4.3
        actions:
          - GoTo: nethack
      - key: w
        name: watch games in progress
        actions:
          - Watch
      - key: q
        name: quit
        actions:
          - Quit
  - id: nethack
    title: NetHack 3.4.3
    entries:
      - key: p
        name: play
        actions:
          - CopyFile:
              - Normal: rgldir/nethackrc
              - UserDir: nethack/nethackrc
              - IgnoreExisting
          - RunGame: nethack
      - key: e
        name: edit nethackrc
        actions:
          - CopyFile:
              - Normal: rgldir/nethackrc
              - UserDir: nethack/nethackrc
              - IgnoreExisting
          - EditFile:
              UserDir: nethack/nethackrc
      - key: r
        name: reset nethackrc
        actions:
          - GoTo: nethack_reset
      - key: q
        name: back
        actions:
          - Return
  - id: nethack_reset
    title: NetHack 3.4.3
    entries:
      - key: p
        name: play
        actions:
          - Return
          - CopyFile:
              - Normal: rgldir/nethackrc
              - UserDir: nethack/nethackrc
              - IgnoreExisting
          - RunGame: nethack
      - key: e
        name: edit nethackrc
        actions:
          - Return
          - CopyFile:
              - Normal: rgldir/nethackrc
              - UserDir: nethack/nethackrc
              - IgnoreExisting
          - EditFile:
              UserDir: nethack/nethackrc
      - key: R
        name: confirm reset?
        actions:
          - Return
          - CopyFile:
              - Normal: rgldir/nethackrc
              - UserDir: nethack/nethackrc
              - OverwriteExisting
          - FlashMessage: the nethackrc file was reset to default
      - key: q
        name: back
        actions:
          - Return
          - Return
